#!/usr/bin/env python3
"""Generate latex/variables.tex — the SINGLE SOURCE OF TRUTH for every number
in the prose. Reads reports/*.json; no number is ever typed into a section file.

Mirrors the variables.tex pattern from the three-layer paper. Fails loudly if a
required report is missing.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

PAPER_DIR = Path(__file__).resolve().parents[1]
REPORTS = PAPER_DIR / "reports"
OUT = PAPER_DIR / "latex" / "variables.tex"


def fail(msg: str) -> None:
    print(f"[variables][FATAL] {msg}", file=sys.stderr)
    sys.exit(1)


def load(name: str, required: bool = True) -> dict | None:
    p = REPORTS / name
    if not p.exists():
        if required:
            fail(f"required report missing: {p}; run compute_validity.py first")
        return None
    return json.loads(p.read_text())


def cmd(name: str, value: str) -> str:
    return f"\\newcommand{{\\{name}}}{{{value}}}\n"


def main() -> None:
    corr = load("correlation.json")
    tau = corr["kendall_tau"]
    rho = corr["spearman_rho"]
    t1 = corr["top1_accuracy"]

    lines = ["% AUTO-GENERATED by scripts/generate_paper_variables.py — DO NOT EDIT BY HAND.\n"]
    lines.append(cmd("nPackages", str(corr["n_packages"])))
    lines.append(cmd("nVariants", str(corr["n_variants"])))
    lines.append(cmd("kendallTau", f"{tau['mean']:.3f}"))
    lines.append(cmd("kendallTauCILow", f"{tau['ci95'][0]:.3f}"))
    lines.append(cmd("kendallTauCIHigh", f"{tau['ci95'][1]:.3f}"))
    lines.append(cmd("spearmanRho", f"{rho['mean']:.3f}"))
    lines.append(cmd("spearmanRhoCILow", f"{rho['ci95'][0]:.3f}"))
    lines.append(cmd("spearmanRhoCIHigh", f"{rho['ci95'][1]:.3f}"))
    lines.append(cmd("topOneAcc", f"{t1['mean'] * 100:.1f}\\%"))
    lines.append(cmd("topOneAccCILow", f"{t1['ci95'][0] * 100:.1f}\\%"))
    lines.append(cmd("topOneAccCIHigh", f"{t1['ci95'][1] * 100:.1f}\\%"))
    lines.append(cmd("randomTopOne", f"{corr['random_top1_baseline'] * 100:.1f}\\%"))
    if "bottom1_accuracy" in corr:
        b1 = corr["bottom1_accuracy"]
        lines.append(cmd("bottomOneAcc", f"{b1['mean'] * 100:.1f}\\%"))
        lines.append(cmd("bottomOneAccCILow", f"{b1['ci95'][0] * 100:.1f}\\%"))
        lines.append(cmd("bottomOneAccCIHigh", f"{b1['ci95'][1] * 100:.1f}\\%"))
    # fraction of A/B tests with a reliable winner (primary / all)
    if corr.get("sensitivity_all_predicted"):
        frac = 100.0 * corr["n_packages"] / corr["sensitivity_all_predicted"]["n_packages"]
        lines.append(cmd("reliableFraction", f"{frac:.1f}\\%"))

    # Sensitivity analysis (all predicted packages), if present in correlation.json.
    sens = corr.get("sensitivity_all_predicted")
    if sens:
        lines.append(cmd("sensNPackages", str(sens["n_packages"])))
        lines.append(cmd("sensNVariants", str(sens["n_variants"])))
        lines.append(cmd("sensKendallTau", f"{sens['kendall_tau']['mean']:.3f}"))
        lines.append(cmd("sensKendallTauCILow", f"{sens['kendall_tau']['ci95'][0]:.3f}"))
        lines.append(cmd("sensKendallTauCIHigh", f"{sens['kendall_tau']['ci95'][1]:.3f}"))
        lines.append(cmd("sensSpearmanRho", f"{sens['spearman_rho']['mean']:.3f}"))

    # Baseline (no-persona) vs panel comparison.
    bc = load("baseline_comparison.json", required=False)
    if bc:
        b = bc["baseline"]
        lines.append(cmd("baseTau", f"{b['tau']['mean']:.3f}"))
        lines.append(cmd("baseTauCILow", f"{b['tau']['ci'][0]:.3f}"))
        lines.append(cmd("baseTauCIHigh", f"{b['tau']['ci'][1]:.3f}"))
        lines.append(cmd("baseRho", f"{b['rho']['mean']:.3f}"))
        lines.append(cmd("baseTopOne", f"{b['top1']['mean']*100:.1f}\\%"))
        lines.append(cmd("baseTopOneCILow", f"{b['top1']['ci'][0]*100:.1f}\\%"))
        lines.append(cmd("baseTopOneCIHigh", f"{b['top1']['ci'][1]*100:.1f}\\%"))

    # H003: signal strength vs validity.
    h = load("h003.json", required=False)
    if h:
        c = h["corr_signal_vs_top1_hit"]
        lines.append(cmd("hThreeN", str(h["n_packages"])))
        lines.append(cmd("hThreeTopOne", f"{c['spearman']:.3f}"))
        lines.append(cmd("hThreeTopOneCILow", f"{c['ci95'][0]:.3f}"))
        lines.append(cmd("hThreeTopOneCIHigh", f"{c['ci95'][1]:.3f}"))

    # Error analysis (why personas hurt): discriminativeness + disagreement counts.
    ea = load("error_analysis.json", required=False)
    if ea:
        disc = ea["discriminativeness_within_pkg_sd"]
        lines.append(cmd("baseSpreadSD", f"{disc['baseline_mean_sd']:.3f}"))
        lines.append(cmd("personaSpreadSD", f"{disc['persona_mean_sd']:.3f}"))
        lines.append(cmd("nBaseRightPersonaWrong", str(ea["n_baseline_right_persona_wrong"])))
        lines.append(cmd("eaNPackages", str(ea["n_packages"])))

    # Cross-dataset replication headline macros.
    rep = load("replication.json", required=False)
    if rep:
        def gap(d):
            return d["baseline"]["kendall_tau"]["mean"] - d["persona"]["kendall_tau"]["mean"]
        up = [k for k in ("exploratory", "holdout", "confirmatory") if k in rep]
        if up:
            gaps = [gap(rep[k]) for k in up]
            lines.append(cmd("repGapMin", f"{min(gaps):.2f}"))
            lines.append(cmd("repGapMax", f"{max(gaps):.2f}"))
            lines.append(cmd("repNDatasets", str(len(rep))))
        if "confirmatory" in rep:
            c = rep["confirmatory"]
            lines.append(cmd("confNPackages", str(c["persona"]["n"])))
            lines.append(cmd("confPersonaTau", f"{c['persona']['kendall_tau']['mean']:.3f}"))
            lines.append(cmd("confBaselineTau", f"{c['baseline']['kendall_tau']['mean']:.3f}"))
        if "mind-news" in rep:
            lines.append(cmd("mindGap", f"{gap(rep['mind-news']):.3f}"))

    # Baseline within-package tie behaviour (transparency / conservative-bound note).
    ties = load("baseline_ties.json", required=False)
    if ties:
        lines.append(cmd("baseTieRate", f"{ties['tie_rate']*100:.1f}\\%"))
        lines.append(cmd("baseTopOneFair", f"{ties['top1_fair_tiebreak']*100:.1f}\\%"))
        lines.append(cmd("baseTopOneNonDegen", f"{ties['top1_non_degenerate']*100:.1f}\\%"))

    # Seed-stability check.
    st = load("stability.json", required=False)
    if st:
        lines.append(cmd("stabTauSD", f"{st['tau_sd']:.3f}"))
        lines.append(cmd("stabTopOneSD", f"{st['top1_sd']:.3f}"))

    # Cross-family robustness (a second, non-Gemini model family: OpenAI gpt-4.1).
    xf = load("crossfamily_gpt41.json", required=False)
    if xf:
        pg = xf["paired_gap"]
        lines.append(cmd("xfModel", "gpt-4.1"))
        lines.append(cmd("xfN", str(xf["persona_panel"]["n_packages"])))
        lines.append(cmd("xfPairedN", str(pg["n_paired"])))
        lines.append(cmd("xfPersonaTau", f"{xf['persona_panel']['kendall_tau']['mean']:.3f}"))
        lines.append(cmd("xfBaselineTau", f"{xf['no_persona_baseline']['kendall_tau']['mean']:.3f}"))
        lines.append(cmd("xfPersonaTop", f"{xf['persona_panel']['top1_accuracy']['mean']*100:.1f}\\%"))
        lines.append(cmd("xfBaselineTop", f"{xf['no_persona_baseline']['top1_accuracy']['mean']*100:.1f}\\%"))
        lines.append(cmd("xfGapTau", f"{pg['gap_tau']['mean']:+.3f}"))
        lines.append(cmd("xfGapTauCILow", f"{pg['gap_tau']['ci95'][0]:.3f}"))
        lines.append(cmd("xfGapTauCIHigh", f"{pg['gap_tau']['ci95'][1]:.3f}"))
        lines.append(cmd("xfGapTopPP", f"{pg['gap_top1']['mean']*100:+.1f}"))
        lines.append(cmd("xfGapTopPPCILow", f"{pg['gap_top1']['ci95'][0]*100:.1f}"))
        lines.append(cmd("xfGapTopPPCIHigh", f"{pg['gap_top1']['ci95'][1]*100:.1f}"))

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("".join(lines))
    print(f"[variables] wrote {OUT} ({len(lines) - 1} macros)")


if __name__ == "__main__":
    main()
