#!/usr/bin/env python3
"""Generate latex/tables/cross_model_gap.tex from reports/cross_model_gap.json: per-model
persona vs no-persona baseline (Kendall tau, top-1), showing the gap is consistent across tiers.
No hand-edited tables."""
from __future__ import annotations

import json
import sys
from pathlib import Path

PAPER_DIR = Path(__file__).resolve().parents[1]
REPORT = PAPER_DIR / "reports" / "cross_model_gap.json"
OUT = PAPER_DIR / "latex" / "tables" / "cross_model_gap.tex"


def main() -> None:
    if not REPORT.exists():
        print(f"[cm-table][FATAL] missing {REPORT}", file=sys.stderr); sys.exit(1)
    d = json.loads(REPORT.read_text())
    n = next(iter(d.values()))["n"]
    rows = []
    for model, r in d.items():
        rows.append(f"    \\texttt{{{model}}} & {r['persona_tau']:.3f} & {r['baseline_tau']:.3f} "
                    f"& $+{r['gap']:.3f}$ \\\\\n")
    tex = [
        "% AUTO-GENERATED by scripts/generate_crossmodel_table.py — DO NOT EDIT BY HAND.\n",
        "\\begin{table*}[t]\n  \\centering\n",
        f"  \\caption{{Cross-model robustness ($n={n}$ reliable packages, Kendall $\\tau$). The "
        "no-persona baseline beats the persona panel on every model tier; persona conditioning "
        "hurts regardless of model.}\n  \\label{tab:cross_model_gap}\n",
        "  \\small\n",
        "  \\begin{tabular}{lccc}\n    \\toprule\n",
        "    Model & Persona $\\tau$ & Baseline $\\tau$ & Gap \\\\\n    \\midrule\n",
        *rows, "    \\bottomrule\n  \\end{tabular}\n\\end{table*}\n",
    ]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("".join(tex))
    print(f"[cm-table] wrote {OUT}")


if __name__ == "__main__":
    main()
