#!/usr/bin/env python3
"""Generate latex/tables/validity.tex (tab:validity, RQ1) — the headline comparison of the
no-persona baseline vs. the persona panel — from reports/baseline_comparison.json, falling back
to the panel-only result in reports/correlation.json if the baseline is absent.

No hand-edited tables; re-running on unchanged reports yields a byte-stable file.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

PAPER_DIR = Path(__file__).resolve().parents[1]
REPORTS = PAPER_DIR / "reports"
OUT = PAPER_DIR / "latex" / "tables" / "validity.tex"


def fail(msg: str) -> None:
    print(f"[table][FATAL] {msg}", file=sys.stderr)
    sys.exit(1)


def cell(d: dict, pct: bool = False) -> str:
    s, u, p = (100, "\\%", 1) if pct else (1, "", 3)
    ci = d.get("ci95", d.get("ci"))   # accept {"mean","ci95"} or {"mean","ci"}
    return f"{d['mean']*s:.{p}f}{u} [{ci[0]*s:.{p}f}, {ci[1]*s:.{p}f}]"


def main() -> None:
    comp = REPORTS / "baseline_comparison.json"
    corr = json.loads((REPORTS / "correlation.json").read_text())
    rand = corr["random_top1_baseline"]
    n = corr["n_packages"]

    if comp.exists():
        d = json.loads(comp.read_text())
        b, p = d["baseline"], d["panel"]
        rows = [
            f"    No-persona baseline & {cell(b['top1'], pct=True)} & {cell(b['tau'])} & {cell(b['rho'])} \\\\\n",
            f"    Persona panel & {cell(p['top1'], pct=True)} & {cell(p['tau'])} & {cell(p['rho'])} \\\\\n",
        ]
        caption = (f"Headline result: a no-persona zero-shot ranker vs.\\ the persona panel on the "
                   f"reliable-winner packages ($n={n}$). The no-persona baseline is substantially "
                   f"better on every metric (non-overlapping CIs). Random top-1 baseline "
                   f"{rand*100:.1f}\\%. 95\\% bootstrap CIs.")
    else:
        t1, tau, rho = corr["top1_accuracy"], corr["kendall_tau"], corr["spearman_rho"]
        rows = [f"    Persona panel & {cell(t1, pct=True)} & {cell(tau)} & {cell(rho)} \\\\\n"]
        caption = (f"Within-package ranking validity of the persona panel ($n={n}$). Random top-1 "
                   f"baseline {rand*100:.1f}\\%. 95\\% bootstrap CIs.")

    tex = [
        "% AUTO-GENERATED by scripts/generate_validity_table.py — DO NOT EDIT BY HAND.\n",
        "\\begin{table*}[t]\n  \\centering\n",
        f"  \\caption{{{caption}}}\n  \\label{{tab:validity}}\n",
        "  \\small\n",
        "  \\begin{tabular}{lccc}\n    \\toprule\n",
        "    Method & Top-1 [95\\% CI] & Kendall $\\tau$ [95\\% CI] & Spearman $\\rho$ [95\\% CI] \\\\\n",
        "    \\midrule\n", *rows, "    \\bottomrule\n  \\end{tabular}\n\\end{table*}\n",
    ]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("".join(tex))
    print(f"[table] wrote {OUT}")


if __name__ == "__main__":
    main()
