#!/usr/bin/env python3
"""Generate latex/tables/model_comparison.tex from reports/pilot_model_comparison.json
(the 3-model pilot). No hand-edited tables."""
from __future__ import annotations

import json
import sys
from pathlib import Path

PAPER_DIR = Path(__file__).resolve().parents[1]
REPORT = PAPER_DIR / "reports" / "pilot_model_comparison.json"
OUT = PAPER_DIR / "latex" / "tables" / "model_comparison.tex"


def main() -> None:
    if not REPORT.exists():
        print(f"[pilot-table][FATAL] missing {REPORT}", file=sys.stderr); sys.exit(1)
    d = json.loads(REPORT.read_text())
    rows = []
    n = None
    for model, r in sorted(d.items()):
        n = r["n_packages"]
        def f(x):
            return f"{x['mean']:.3f} [{x['ci95'][0]:.2f}, {x['ci95'][1]:.2f}]"
        rows.append(f"    \\texttt{{{model}}} & {f(r['top1_accuracy'])} & {f(r['kendall_tau'])} "
                    f"& {f(r['spearman_rho'])} \\\\\n")
    tex = [
        "% AUTO-GENERATED by scripts/generate_pilot_table.py — DO NOT EDIT BY HAND.\n",
        "\\begin{table*}[t]\n  \\centering\n",
        f"  \\caption{{Pilot model comparison on a common subset ($n={n}$ packages). The "
        "validity intervals overlap across model tiers, so the cheapest model was selected. "
        "95\\% bootstrap CIs.}\n",
        "  \\label{tab:model_comparison}\n",
        "  \\small\n",
        "  \\begin{tabular}{lccc}\n    \\toprule\n",
        "    Model & Top-1 & Kendall $\\tau$ & Spearman $\\rho$ \\\\\n    \\midrule\n",
        *rows,
        "    \\bottomrule\n  \\end{tabular}\n\\end{table*}\n",
    ]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("".join(tex))
    print(f"[pilot-table] wrote {OUT}")


if __name__ == "__main__":
    main()
