#!/usr/bin/env python3
"""Generate latex/tables/replication.tex from reports/replication.json: per-dataset persona vs
no-persona baseline (Kendall tau, gap, lift captured), showing the finding replicates across
independent Upworthy splits and a different domain (MIND). No hand-edited tables."""
from __future__ import annotations

import json
import sys
from pathlib import Path

PAPER_DIR = Path(__file__).resolve().parents[1]
REPORT = PAPER_DIR / "reports" / "replication.json"
OUT = PAPER_DIR / "latex" / "tables" / "replication.tex"

LABELS = {
    "exploratory": "Upworthy exploratory (2013--15)",
    "holdout": "Upworthy holdout (2013--15)",
    "confirmatory": "Upworthy confirmatory (2013--15)",
    "mind-news": "MIND news (2019)",
    "reddit-titles": "Reddit titles (2008--12)",
}
ORDER = ["exploratory", "holdout", "confirmatory", "mind-news", "reddit-titles"]


def main() -> None:
    if not REPORT.exists():
        print(f"[rep-table][FATAL] missing {REPORT}", file=sys.stderr); sys.exit(1)
    d = json.loads(REPORT.read_text())
    rows = []
    for k in ORDER:
        if k not in d:
            continue
        p, b = d[k]["persona"], d[k]["baseline"]
        gap = b["kendall_tau"]["mean"] - p["kendall_tau"]["mean"]
        rows.append(f"    {LABELS[k]} & {p['n']} & {p['kendall_tau']['mean']:.3f} "
                    f"& {b['kendall_tau']['mean']:.3f} & ${gap:+.3f}$ & "
                    f"{p['lift_captured']['mean']:.2f}/{b['lift_captured']['mean']:.2f} \\\\\n")
    tex = [
        "% AUTO-GENERATED by scripts/generate_replication_table.py — DO NOT EDIT BY HAND.\n",
        "\\begin{table*}[t]\n  \\centering\n",
        "  \\caption{Replication across three independent Upworthy splits and two further "
        "platforms/domains (MIND news, 2019; Reddit title reposts, 2008--12). The no-persona "
        "baseline beats or matches the persona panel everywhere; the advantage is large on "
        "controlled copy A/B tests, small on cross-article news, and vanishes on Reddit where "
        "upvotes are not title-predictable (both $\\tau\\approx0$). Lift = fraction of achievable CTR lift captured "
        "by the top-1 pick (persona/baseline). Kendall $\\tau$ on significant-winner packages. For "
        "cross-dataset comparability all rows use a single draw per persona; the exploratory split's "
        "multi-draw primary estimate is in Table~\\ref{tab:validity}.}\n",
        "  \\label{tab:replication}\n",
        "  \\small\n",
        "  \\begin{tabular}{lccccc}\n    \\toprule\n",
        "    Dataset & $n$ & Persona $\\tau$ & Baseline $\\tau$ & Gap & Lift p/b \\\\\n    \\midrule\n",
        *rows, "    \\bottomrule\n  \\end{tabular}\n\\end{table*}\n",
    ]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("".join(tex))
    print(f"[rep-table] wrote {OUT}")


if __name__ == "__main__":
    main()
