#!/usr/bin/env python3
"""Generate supplementary LaTeX tables (artifact-first):
  tables/persona_panel.tex   — the full 10-persona panel (from data/persona_panel.json)
  tables/error_examples.tex  — example A/B tests where the baseline ranks the real winner #1
                               but the persona panel does not (from reports/error_analysis.json)
No hand-edited tables.
"""
from __future__ import annotations

import json
from pathlib import Path

PAPER_DIR = Path(__file__).resolve().parents[1]
TABLES = PAPER_DIR / "latex" / "tables"
TABLES.mkdir(parents=True, exist_ok=True)


def esc(s: str) -> str:
    for a, b in [("&", "\\&"), ("%", "\\%"), ("_", "\\_"), ("#", "\\#"), ("$", "\\$")]:
        s = s.replace(a, b)
    return s


def persona_table() -> None:
    panel = json.loads((PAPER_DIR / "data" / "persona_panel.json").read_text())["personas"]
    rows = [f"    {p['id']} & {p['age_group']}, {p['gender'][:1].upper()}, {p['platform']} "
            f"& {esc(p['description'])} \\\\\n" for p in panel]
    tex = [
        "% AUTO-GENERATED by scripts/generate_supplementary_tables.py — DO NOT EDIT BY HAND.\n",
        "\\begin{table*}[t]\n  \\centering\n",
        "  \\caption{The full fixed persona panel ($P{=}10$), grounded in the Upworthy-era audience "
        "demographics~\\citep{holcomb2013newsuse}, with the verbatim behavioural descriptions used "
        "in the prompt (for replicability). News engagement and political lean are in the "
        "replication package (\\texttt{data/persona\\_panel.json}).}\n  \\label{tab:persona_panel}\n",
        "  \\small\n",
        "  \\begin{tabular}{lp{2.6cm}p{10.5cm}}\n    \\toprule\n",
        "    ID & Demographics & Behavioural description (verbatim) \\\\\n    \\midrule\n",
        *rows, "    \\bottomrule\n  \\end{tabular}\n\\end{table*}\n",
    ]
    (TABLES / "persona_panel.tex").write_text("".join(tex))
    print("wrote tables/persona_panel.tex")


def error_examples_table() -> None:
    ea = json.loads((PAPER_DIR / "reports" / "error_analysis.json").read_text())
    rows = []
    for e in ea["examples"][:10]:
        h = esc(e["winner_headline"])
        if len(h) > 70:
            h = h[:67] + "..."
        rows.append(f"    {h} & {e['winner_real_ctr']*100:.2f}\\% & {e['n_variants']} \\\\\n")
    tex = [
        "% AUTO-GENERATED by scripts/generate_supplementary_tables.py — DO NOT EDIT BY HAND.\n",
        "\\begin{table}[t]\n  \\centering\n",
        "  \\caption{Examples of real winning headlines that the no-persona baseline ranked first "
        "but the persona panel did not (of \\nBaseRightPersonaWrong{} such cases). These are "
        "typically curiosity-gap / feel-good headlines the base model recognises as clickable.}\n"
        "  \\label{tab:error_examples}\n",
        "  \\small\n",
        "  \\begin{tabular}{p{5.6cm}cc}\n    \\toprule\n",
        "    Real winning headline & CTR & \\#var \\\\\n    \\midrule\n",
        *rows, "    \\bottomrule\n  \\end{tabular}\n\\end{table}\n",
    ]
    (TABLES / "error_examples.tex").write_text("".join(tex))
    print("wrote tables/error_examples.tex")


if __name__ == "__main__":
    persona_table()
    error_examples_table()
