#!/usr/bin/env python3
"""Generate latex/tables/h5_aggregation.tex (tab:h5agg) from reports/h5_aggregation.csv.

Robustness of the persona-panel result to the aggregation rule (H5): six rules applied to the
SAME per-persona observations, with the no-persona baseline as reference. No hand-edited tables;
re-running on an unchanged CSV yields a byte-stable file. Run analyze_h5_aggregation.py first.
"""
from __future__ import annotations

import csv
import sys
from pathlib import Path

PAPER_DIR = Path(__file__).resolve().parents[1]
SRC = PAPER_DIR / "reports" / "h5_aggregation.csv"
OUT = PAPER_DIR / "latex" / "tables" / "h5_aggregation.tex"

LABEL = {
    "baseline_no_persona": "No-persona baseline",
    "mean": "Panel mean \\emph{(primary)}",
    "median": "Panel median",
    "trimmed20": "Trimmed mean (20\\%)",
    "zmean": "Per-persona $z$-mean",
    "borda": "Borda (rank fusion)",
    "condorcet": "Condorcet (pairwise)",
}
ORDER = ["baseline_no_persona", "mean", "median", "trimmed20", "zmean", "borda", "condorcet"]


def main() -> None:
    if not SRC.exists():
        sys.exit(f"[table][FATAL] {SRC} missing; run scripts/analyze_h5_aggregation.py first")
    rows = {r["rule"]: r for r in csv.DictReader(SRC.open())}
    n = rows["mean"]["n"]

    body = []
    for rule in ORDER:
        r = rows[rule]
        tau = f"{float(r['kendall_tau']):.3f} [{float(r['tau_lo']):.3f}, {float(r['tau_hi']):.3f}]"
        t1 = f"{float(r['top1'])*100:.1f}\\% [{float(r['top1_lo'])*100:.1f}, {float(r['top1_hi'])*100:.1f}]"
        line = f"    {LABEL[rule]} & {tau} & {t1} \\\\\n"
        if rule == "baseline_no_persona":
            line += "    \\midrule\n"
        body.append(line)

    caption = (
        f"H5 --- robustness to the aggregation rule. Six rules applied to the \\emph{{same}} "
        f"per-persona observations on the reliable-winner packages ($n={n}$), with the no-persona "
        f"baseline as reference. No rule recovers baseline validity: every persona CI upper bound "
        f"sits below the baseline. Median best mitigates the panel mean's outlier sensitivity "
        f"($\\tau$ $0.084\\!\\to\\!0.141$), while rank-fusion (Borda) and pairwise majority "
        f"(Condorcet) --- which use only persona \\emph{{orderings}} --- do not help, locating the "
        f"failure in genuine mis-ordering rather than per-persona scale. The mean-row top-1 is "
        f"recomputed here from draw-collapsed per-persona scores and can differ from "
        f"Table~\\ref{{tab:validity}}'s multi-draw primary estimate by a single package through "
        f"tie-breaking; the rank coefficient $\\tau$ is identical. 95\\% bootstrap CIs.")

    tex = [
        "% AUTO-GENERATED by scripts/generate_h5_table.py — DO NOT EDIT BY HAND.\n",
        "\\begin{table}[t]\n  \\centering\n",
        f"  \\caption{{{caption}}}\n  \\label{{tab:h5agg}}\n",
        "  \\small\n  \\resizebox{\\columnwidth}{!}{%\n  \\begin{tabular}{lcc}\n    \\toprule\n",
        "    Aggregation & Kendall $\\tau$ [95\\% CI] & Top-1 [95\\% CI] \\\\\n",
        "    \\midrule\n", *body, "    \\bottomrule\n  \\end{tabular}}\n\\end{table}\n",
    ]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("".join(tex))
    print(f"[table] wrote {OUT}")


if __name__ == "__main__":
    main()
